export const FAKE_POPULARS = [
  {
    backdrop_path: "/9xxLWtnFxkpJ2h1uthpvCRK6vta.jpg",
    first_air_date: "1999-09-20",
    genre_ids: [80, 18, 9648],
    id: 2734,
    name: "Law & Order: Special Victims Unit",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Law & Order: Special Victims Unit",
    overview:
      "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.",
    popularity: 4909.172,
    poster_path: "/ywBt4WKADdMVgxTR1rS2uFwMYTH.jpg",
    vote_average: 8,
    vote_count: 3330,
  },
  {
    backdrop_path: "/yYNa1nqvNK94xZz3eKyfvZdAvPi.jpg",
    first_air_date: "2020-11-02",
    genre_ids: [10766],
    id: 112470,
    name: "Here it all begins",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Ici tout commence",
    overview: "",
    popularity: 4714.599,
    poster_path: "/60cqjI590JKXCAABqCStVmSBGET.jpg",
    vote_average: 7.3,
    vote_count: 12,
  },
  {
    backdrop_path: "/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg",
    first_air_date: "1952-12-26",
    genre_ids: [10763],
    id: 94722,
    name: "Tagesschau",
    origin_country: ["DE"],
    original_language: "de",
    original_name: "Tagesschau",
    overview:
      "German daily news program, the oldest still existing program on German television.",
    popularity: 3096.593,
    poster_path: "/7dFZJ2ZJJdcmkp05B9NWlqTJ5tq.jpg",
    vote_average: 7.5,
    vote_count: 118,
  },
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2984.62,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 7.1,
    vote_count: 113,
  },
  {
    backdrop_path: "/ds1n5P0Y92cTh6UpbcA89hxM96a.jpg",
    first_air_date: "2005-03-27",
    genre_ids: [18],
    id: 1416,
    name: "Grey's Anatomy",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    popularity: 2865.136,
    poster_path: "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
    vote_average: 8.3,
    vote_count: 9396,
  },
  {
    backdrop_path: null,
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215315,
    name: "Rabb Se Hai Dua",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "रब्ब से है दुआ",
    overview:
      "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
    popularity: 2857.858,
    poster_path: "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
    vote_average: 6.7,
    vote_count: 71,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "Teri Meri Doriyaann",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "तेरी मेरी डोरियाँ",
    overview:
      "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
    popularity: 2838.24,
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 7.2,
    vote_count: 97,
  },
  {
    backdrop_path: "/jtAh65bX9Ydy2NFkwTN6V9WSzWb.jpg",
    first_air_date: "2023-02-07",
    genre_ids: [18],
    id: 220525,
    name: "Maitree",
    origin_country: [],
    original_language: "hi",
    original_name: "मैत्री",
    overview: "",
    popularity: 2481.322,
    poster_path: "/k57vsZ5Pl80WRR02ahgC3QLdhhL.jpg",
    vote_average: 8,
    vote_count: 26,
  },
  {
    backdrop_path: "/e9n87p3Ax67spq3eUgLB6rjIEow.jpg",
    first_air_date: "2005-09-13",
    genre_ids: [80, 18],
    id: 1911,
    name: "Bones",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Bones",
    overview:
      "Dr. Temperance Brennan and her colleagues at the Jeffersonian's Medico-Legal Lab assist Special Agent Seeley Booth with murder investigations when the remains are so badly decomposed, burned or destroyed that the standard identification methods are useless.",
    popularity: 3025.945,
    poster_path: "/eyTu5c8LniVciRZIOSHTvvkkgJa.jpg",
    vote_average: 8.3,
    vote_count: 2849,
  },
  {
    backdrop_path: "/xXRsKNJHTOGrs5wfYAxkbM2RiyT.jpg",
    first_air_date: "2017-09-25",
    genre_ids: [18],
    id: 71712,
    name: "The Good Doctor",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Good Doctor",
    overview:
      "Shaun Murphy, a young surgeon with autism and savant syndrome, relocates from a quiet country life to join a prestigious hospital's surgical unit. Unable to personally connect with those around him, Shaun uses his extraordinary medical gifts to save lives and challenge the skepticism of his colleagues.",
    popularity: 2709.736,
    poster_path: "/luhKkdD80qe62fwop6sdrXK9jUT.jpg",
    vote_average: 8.5,
    vote_count: 11653,
  },
  {
    backdrop_path: "/m0TiLZ79RR19Zz0AZruQSBeH39x.jpg",
    first_air_date: "2019-07-09",
    genre_ids: [10764],
    id: 90521,
    name: "Love Island",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Love Island",
    overview:
      "American version of the British dating reality competition in which ten singles come to stay in a villa for a few weeks and have to couple up with one another. Over the course of those weeks, they face the public vote and might be eliminated from the show. Other islanders join and try to break up the couples.",
    popularity: 2181.641,
    poster_path: "/kU2y21cls8WargMaX7KI47URMjD.jpg",
    vote_average: 7.4,
    vote_count: 109,
  },
  {
    backdrop_path: "/63XwyHYjIHIm4F8Vg6wyBfDQprc.jpg",
    first_air_date: "2000-10-06",
    genre_ids: [80, 18, 9648],
    id: 1431,
    name: "CSI: Crime Scene Investigation",
    origin_country: ["US"],
    original_language: "en",
    original_name: "CSI: Crime Scene Investigation",
    overview:
      "A Las Vegas team of forensic investigators are trained to solve criminal cases by scouring the crime scene, collecting irrefutable evidence and finding the missing pieces that solve the mystery.",
    popularity: 2292.508,
    poster_path: "/i5hmoRjHNWady4AtAGICTUXknKH.jpg",
    vote_average: 7.7,
    vote_count: 1027,
  },
  {
    backdrop_path: "/5e1MxLWTJh6n4qtYz0vlevOK6qW.jpg",
    first_air_date: "2023-07-03",
    genre_ids: [18],
    id: 229932,
    name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
    overview:
      "Shiv has a rewarding career as a doctor, but his personal life is in tatters. Shakti, an orphan, is a nurturer by nature. Will Shakti heal a broken Shiv?",
    popularity: 1976.48,
    poster_path: "/jHK9bCDefHq43cHvMVUM7SLumYF.jpg",
    vote_average: 8.1,
    vote_count: 40,
  },
  {
    backdrop_path: "/kdF7ZTktLHVVhAhI90uuzqlZqJI.jpg",
    first_air_date: "2023-06-06",
    genre_ids: [18],
    id: 228093,
    name: "Titlie",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Titlie",
    overview:
      "Obsessed by the notion of fairy tale love , Titlie marries her beau Garv . Soon , the picture - perfect romance turns abusive , forcing her to wrestle with reality .",
    popularity: 2014.406,
    poster_path: "/5kZi1LCFugNAeDCWOF3ornGNm2W.jpg",
    vote_average: 8,
    vote_count: 75,
  },
  {
    backdrop_path: "/nVRyd8hlg0ZLxBn9RaI7mUMQLnz.jpg",
    first_air_date: "2005-09-13",
    genre_ids: [18, 9648, 10765],
    id: 1622,
    name: "Supernatural",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Supernatural",
    overview:
      "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
    popularity: 2542.902,
    poster_path: "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg",
    vote_average: 8.3,
    vote_count: 6814,
  },
  {
    backdrop_path: "/qtfMr08KQsWXnCHY0a96N8NpQ2l.jpg",
    first_air_date: "2004-10-05",
    genre_ids: [10759, 16, 10765],
    id: 30984,
    name: "Bleach",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "BLEACH",
    overview:
      "For as long as he can remember, Ichigo Kurosaki has been able to see ghosts. But when he meets Rukia, a Soul Reaper who battles evil spirits known as Hollows, he finds his life is changed forever. Now, with a newfound wealth of spiritual energy, Ichigo discovers his true calling: to protect the living and the dead from evil.",
    popularity: 2017.25,
    poster_path: "/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
    vote_average: 8.4,
    vote_count: 1566,
  },
  {
    backdrop_path: "/wq269s8vzr8xrwrIALtl4UfmN6X.jpg",
    first_air_date: "2023-06-12",
    genre_ids: [],
    id: 228627,
    name: "Do Dil Mil Rahe Hai",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Do Dil Mil Rahe Hai",
    overview:
      "He repels love , she resembles it ! Rishi and Pihu are worlds apart but unaware of the past that connects them . Will fate lead the duo down the road to true love ?",
    popularity: 1982.437,
    poster_path: "/juYg1PQzCmDJYyGtrW0Xbvke1jx.jpg",
    vote_average: 7.4,
    vote_count: 54,
  },
  {
    backdrop_path: "/a1axm2xRYGB35X406AMI51IrhYp.jpg",
    first_air_date: "2012-10-10",
    genre_ids: [18],
    id: 44006,
    name: "Chicago Fire",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Chicago Fire",
    overview:
      "An edge-of-your-seat view into the lives of everyday heroes committed to one of America's noblest professions. For the firefighters, rescue squad and paramedics of Chicago Firehouse 51, no occupation is more stressful or dangerous, yet so rewarding and exhilarating. These courageous men and women are among the elite who forge headfirst into danger when everyone else is running the other way and whose actions make the difference between life and death.",
    popularity: 2790.511,
    poster_path: "/iiI1YU8akLYWdWuX1qHuMYPvSHC.jpg",
    vote_average: 8.4,
    vote_count: 1982,
  },
  {
    backdrop_path: "/2eIlCirgcvEwmCSYh2wDfz5Sxvz.jpg",
    first_air_date: "2013-09-23",
    genre_ids: [18, 80, 9648],
    id: 46952,
    name: "The Blacklist",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Blacklist",
    overview:
      'Raymond "Red" Reddington, one of the FBI\'s most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he\'s made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this "The Blacklist". Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.',
    popularity: 2016.93,
    poster_path: "/r935SMphvXppx5bJjbIBNx02fwc.jpg",
    vote_average: 7.6,
    vote_count: 2779,
  },
  {
    backdrop_path: "/2pOmuq4nkWZzwZbOfZq7CyyQAsM.jpg",
    first_air_date: "2003-09-22",
    genre_ids: [35, 18],
    id: 2691,
    name: "Two and a Half Men",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Two and a Half Men",
    overview:
      "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
    popularity: 1919.017,
    poster_path: "/A9QDK4OWpv41W27kCv0LXe30k9S.jpg",
    vote_average: 7.4,
    vote_count: 2787,
  },
];
