export const FAKE_SEARCH_RESPONSE = [
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    genre_ids: [10765, 18, 10759],
    id: 1399,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    popularity: 783.67,
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    first_air_date: "2011-04-17",
    name: "Game of Thrones",
    vote_average: 8.4,
    vote_count: 21596,
  },
  {
    adult: false,
    backdrop_path: "/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    genre_ids: [10759, 9648, 18],
    id: 93405,
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    popularity: 115.898,
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    first_air_date: "2021-09-17",
    name: "Squid Game",
    vote_average: 7.832,
    vote_count: 12920,
  },
  {
    adult: false,
    backdrop_path: "/8YVsmL6dHacOKb8N44huyAnuIBG.jpg",
    genre_ids: [10764, 35],
    id: 226051,
    origin_country: ["AU"],
    original_language: "en",
    original_name: "The Most Upsetting Guessing Game in the World",
    overview:
      "The 'Most Upsetting Guessing Game' is a comedy/improv guessing game based on 'Party Quirks' from the Aunty Donna Podcast. Each week a 'party host' is selected and tasked with guessing what 'characters' are attending their party. Sounds simple enough? It's not... it's cooked.",
    popularity: 0.993,
    poster_path: "/v2RiOMrnKz4zpVWDwFs0h3wboKD.jpg",
    first_air_date: "2023-05-08",
    name: "The Most Upsetting Guessing Game in the World",
    vote_average: 9,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/2dpk36NSrJctO2Xd5w78ygjeXSN.jpg",
    genre_ids: [18],
    id: 229302,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "トリリオンゲーム",
    overview:
      'Tennoji Haru is an excellent communicator. He is loved by all people regardless of age or gender. He appears like an easygoing person, but he is actually ambitious and will do anything for success. Haru is offered a job with the nation\'s largest IT company "Dragon Bank", but he turns down the offer. Instead, he decides to start his own business with his friend Taira Manabu. His goal is to earn 1 trillion dollars.\n\nMeanwhile, Taira is an excellent engineer with remarkable IT knowledge. Personality-wise, he is quite the opposite of Haru. He\'s passive and has a hard time communicating with people. Due to that, he failed his job interview with "Dragon Bank" and set a new goal of earning 1 trillion dollars with Haru.',
    popularity: 66.552,
    poster_path: "/yKWo0HdvMBo0WRaaAVTBIAgT1tM.jpg",
    first_air_date: "2023-07-14",
    name: "Trillion Game",
    vote_average: 6,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/sxZfrfSJ0rXDpoLCDty6UMWNF6Q.jpg",
    genre_ids: [18, 80],
    id: 13967,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "LIAR GAME",
    overview:
      "Nao Kanzaki, a student, was blackmailed into joining a \"Liar Game\" and ended up losing 100 million yen. In order to repay the debt, she enlists the help of Shin'ichi Akiyama, a genius swindler who was only recently released from jail for bankrupting one of Japan's largest scam companies.",
    popularity: 18.691,
    poster_path: "/oSaZVSF5exQKXHIDotbTqA8ZntJ.jpg",
    first_air_date: "2007-04-14",
    name: "LIAR GAME",
    vote_average: 7.8,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/lpuN1zRlmTIITsvwVhGJLH5h4iw.jpg",
    genre_ids: [10763, 35],
    id: 45974,
    origin_country: ["DE"],
    original_language: "de",
    original_name: "Game One",
    overview: "",
    popularity: 36.68,
    poster_path: "/4lD2JDlALVVfcERgWb1Jpnq7NRe.jpg",
    first_air_date: "2006-09-27",
    name: "Game One",
    vote_average: 7,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/2asPUwxDTVnEzLs5G37u0mdg5I.jpg",
    genre_ids: [16, 10765, 10759, 35],
    id: 60808,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ノーゲーム･ノーライフ",
    overview:
      'This is a surreal comedy that follows Sora and Shiro, shut-in NEET siblings and the online gamer duo behind the legendary username "Kuuhaku." They view the real world as just another lousy game; however, a strange e-mail challenging them to a chess match changes everything—the brother and sister are plunged into an otherworldly realm where they meet Tet, the God of Games.\n\nThe mysterious god welcomes the two to Disboard, a world where all forms of conflict are settled through high-stake games. This system works thanks to a fundamental rule wherein each party must wager something they deem to be of equal value to the other party\'s wager. In this strange land where the very idea of humanity is reduced to child’s play, the indifferent genius gamer duo of Sora and Shiro have finally found a real reason to keep playing games: to unite the sixteen races of Disboard, defeat Tet, and become the gods of this new, gaming-is-everything world.',
    popularity: 25.225,
    poster_path: "/kN4BhRDbP3b1nuxpYC443jVLEh5.jpg",
    first_air_date: "2014-04-09",
    name: "No Game No Life",
    vote_average: 8.277,
    vote_count: 565,
  },
  {
    adult: false,
    backdrop_path: "/m9FDZBqkyRhBVWDldkpaNq6zZxQ.jpg",
    genre_ids: [16, 10765, 10759],
    id: 134843,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "デジモンゴーストゲーム",
    overview:
      'High school freshman Hiro Amanokawa activates a mysterious device left behind by his father called "Digivice" that makes unknown creatures that cannot be seen by ordinary people, the Digimon, visible to his eyes. This is the story of this other side of the world that nobody is aware of. With their friends, Hiro and Gammamon dive into the mysterious world where these creatures live.',
    popularity: 54.463,
    poster_path: "/tFI1gE0idyh4E1bvRbHhL3M96tz.jpg",
    first_air_date: "2021-10-03",
    name: "Digimon Ghost Game",
    vote_average: 7.083,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/c0oFoz7PttzMLsQOQn54Lcu8V9d.jpg",
    genre_ids: [16, 35],
    id: 139512,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "乙女ゲー世界はモブに厳しい世界です",
    overview:
      "An ordinary office worker is reincarnated as Leon into a particularly punishing dating sim video game, where women reign supreme and only beautiful men have a seat at the table. But Leon has a secret weapon: he remembers everything from his past life, which includes a complete playthrough of the very game in which he is now trapped. Watch Leon spark a revolution to change this new world in order to fulfill his ultimate desire...of living a quiet, easy life in the countryside!",
    popularity: 30.716,
    poster_path: "/8AhHtqY4yPquNrprkVbzUKw8kRh.jpg",
    first_air_date: "2022-04-03",
    name: "Trapped in a Dating Sim: The World of Otome Games Is Tough for Mobs",
    vote_average: 7.2,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: "/q1o1JehssonxPGRSpHCjmfAFMv3.jpg",
    genre_ids: [10764],
    id: 123473,
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "출장 십오야",
    overview:
      "A webseries where Na Young Seok, a variety show producer, caters people his iconic games from 'New Journey to the West'.",
    popularity: 75.289,
    poster_path: "/wkF2M0ApsqscicSzsMZglxNBL2S.jpg",
    first_air_date: "2021-03-12",
    name: "The Game Caterers",
    vote_average: 8.7,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/qs0qbyMeFTYjsVlcn3oyjNyciFx.jpg",
    genre_ids: [35],
    id: 17338,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ゲームセンターCX",
    overview:
      "Shinya Arino, a member of comedy duo Yoiko, plays Japan's most popular video games and records his progress as he works through a time limit, usually lasting up to one day. He is supported by his Assistant Directors and Staff, both via moral support and actual gameplay. He also gets the chance to interview game designers and to play arcade games occasionally.",
    popularity: 32.428,
    poster_path: "/jYyKjtYuKKEzQrkCa7nrTBc9wB9.jpg",
    first_air_date: "2003-11-04",
    name: "GameCenter CX",
    vote_average: 9,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/rSDv2x1LRheZd27mDrj94hU3bs1.jpg",
    genre_ids: [16, 9648, 80],
    id: 69891,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "乱歩奇譚: Game of Laplace",
    overview:
      "The story takes place at a certain middle school where several murder cases take place. Kobayashi, a boy who goes to this school, meets genius detective Akechi, who comes to the school to investigate. Kobayashi takes an interest in Akechi and, in spite of his friend Hashiba's worries, he volunteers to be Akechi's assistant.",
    popularity: 7.326,
    poster_path: "/7L2tSZt6SNwOjqwLn43QeNZ9SBM.jpg",
    first_air_date: "2015-07-03",
    name: "Rampo Kitan: Game of Laplace",
    vote_average: 6.4,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/rBfsSKN0XvWgojA0VtvMrnLQoEM.jpg",
    genre_ids: [10759],
    id: 107703,
    origin_country: ["RU"],
    original_language: "ru",
    original_name: "Игра на выживание",
    overview:
      "Sixteen contestants of a new survival show are taken to the Siberian taiga to compete for the price of one million euros. The rules are simple: no food, personal belongings, electricity, communications and civilization for hundreds of kilometers around. The one remains wins. Soon TV project turns into a deadly game, where LIFE becomes the main prize... What is it? Is it sick TV script? Who is behind this? And who can survive without losing their humanity?",
    popularity: 15.593,
    poster_path: "/chLNbjo3QV6Sw47dH5W8ZxArBYb.jpg",
    first_air_date: "2020-08-31",
    name: "The Big Game",
    vote_average: 8.3,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/fMT0SK0KCTIbHfwik8T67G0kC89.jpg",
    genre_ids: [18, 16, 9648],
    id: 65949,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ジョーカー・ゲーム",
    overview:
      'Taking place in the year 1937 on the eve of World War II, the story involves a mysterious spy training organization known as the "D Agency." The organization is established by Lieutenant Colonel Yuuki from the Imperial Japanese Army. His ideals lead him to recruit people beyond military academy graduates and personnel, while training them to become skilled agents in arts of manipulation. These agents would become a specialized team to conduct operations. One such antihero agent, under the name Jirou Gamou, goes on a harrowing mission to uncover secret documents titled "Black Notes," while battling forces from within and without his own ranks.',
    popularity: 21.51,
    poster_path: "/4li82SvY2zhc2PsvmHU07C30dtv.jpg",
    first_air_date: "2016-04-05",
    name: "Joker Game",
    vote_average: 6.6,
    vote_count: 28,
  },
  {
    adult: false,
    backdrop_path: "/8xH4GUHWyOnDRv3TUlt7jBKTnHd.jpg",
    genre_ids: [16, 9648, 10759, 10765],
    id: 85942,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "ダーウィンズゲーム",
    overview:
      'Sudou Kaname, an ordinary high school student, receives an invitation email to try a mysterious app called "Darwin\'s Game." Kaname, upon launching the app, is drawn into a game where players fight one another using superpowers called Sigils. Without knowing the reason for all this, can Kaname survive furious battles against the powerful players who attack him?',
    popularity: 24.994,
    poster_path: "/dk5QFqxVt6WnTWTiK6hHdkL2SMz.jpg",
    first_air_date: "2020-01-04",
    name: "Darwin's Game",
    vote_average: 7.748,
    vote_count: 137,
  },
  {
    adult: false,
    backdrop_path: "/8soU8PiR0ouAqspEK54DUduEu72.jpg",
    genre_ids: [16, 18],
    id: 74183,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "王様ゲーム The Animation",
    overview:
      "Kanazawa Nobuaki has transferred to a high school far from where he used to live. Due to an incident at his old school, Nobuaki is afraid of getting close to his new classmates and keeps himself at a distance, but he starts opening up because of a sports day inter-class relay. Then a single text message from someone calling themselves the \"King\" is sent to everyone in class. Nobuaki's classmates think it's a simple prank and don't take it seriously - but Nobuaki knows that a death game is about to begin, and struggles to oppose it...",
    popularity: 15.17,
    poster_path: "/4U623rLgz8a3gbBMMys6pUlvrin.jpg",
    first_air_date: "2017-10-05",
    name: "Ousama Game The Animation",
    vote_average: 7.661,
    vote_count: 96,
  },
  {
    adult: false,
    backdrop_path: "/xOi6lRbJh3fBFur8QuxTyGzOqiH.jpg",
    genre_ids: [16, 18, 9648, 10759, 10765],
    id: 112940,
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "出会って5秒でバトル",
    overview:
      'It was just a usual morning.\n\nAkira Shiroyanagi, a high schooler who loves games and Konpeito (Japanese sweets), has suddenly been dragged into a battlefield by a mysterious girl who calls herself Mion. The participants are told that they are "erased from the family register, involved in an experiment, and gained certain powers."\n\nAkira is determined to win the game with his newfound powers and destroy the organization. Armed with a power no one expects and his "brain" skills, the new period of intelligence battle begins!',
    popularity: 20.123,
    poster_path: "/nGuTtEc5q3pO6Kl2Pmszc9IwEe.jpg",
    first_air_date: "2021-07-13",
    name: "Battle Game in 5 Seconds",
    vote_average: 8.046,
    vote_count: 97,
  },
  {
    adult: false,
    backdrop_path: "/aRxd1y7mKeQCVg5vhfSswVumMAW.jpg",
    genre_ids: [10764],
    id: 62595,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Guy's Grocery Games",
    overview:
      'Guy Fieri sends four talented chefs running through the aisles in a high stakes, high skills, grocery store cooking competition. The chefs are hit by real-world challenges like finding workarounds when all the essential ingredients are suddenly "out-of-stock" or having to create a masterpiece when you can only cook with "5 items or less" or on a $10 budget. In the end, the food does the talking, as the last chef standing has the chance to make some serious dough!',
    popularity: 49.469,
    poster_path: "/dNg2v7SQLOOYn23rc5dJLgSDgYh.jpg",
    first_air_date: "2013-10-20",
    name: "Guy's Grocery Games",
    vote_average: 5.5,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/fnOv749ek9yiS865xioiq1e62bo.jpg",
    genre_ids: [],
    id: 109423,
    origin_country: ["HK"],
    original_language: "cn",
    original_name: "騙中傳奇",
    overview: "",
    popularity: 2.599,
    poster_path: "/keZN60vOePXIoQ4EnkvrAleELdR.jpg",
    first_air_date: "1999-09-09",
    name: "Game of Deceit",
    vote_average: 8.3,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/iLPgUJqo3sGkwfWa7xvYMyV4Nub.jpg",
    genre_ids: [18, 9648],
    id: 105213,
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Boca a Boca",
    overview:
      'At a high school in a rural, isolated ranching community, families panic when teens contract a mysterious "kissing disease" that quickly spreads.',
    popularity: 13.924,
    poster_path: "/i0Gmbo25STtJBIxTFyQpqw7Thxl.jpg",
    first_air_date: "2020-07-17",
    name: "Kissing Game",
    vote_average: 6.984,
    vote_count: 257,
  },
];
